dumper/app/build.gradle
dumper/buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle

The runtime dependency is required through `spring-jdbc`, if not provided the tool will fail as follows:
```
java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
```

Add missing runtime dependency on jcl-over-slf4j

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/DefaultArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/MetadataConnector.java

Tool name in command line help (i.e. `--help`) and default output name pattern updated to be coherent with the repository name.

Change default output file name pattern, change product name in help.

---

client/batch_sql_translator.py
client/config.yaml
client/config_parser.py

This PR allows users to specify `default_database` and `schema_search_path` in the `config.yaml` file.
I was planning on using this in the codelab I am working on.

Add support for default_database and schema_search_path

---

client/README.md

We should not put TODOs in readme since it's acting as public docs. I also don't think we would like to include metadata dumper instruction in the exemplary client, since it may increase the time to value path.

remove TODOs in readme

---

dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java

This should help mitigate the exception: `Storage schema reading not supported`, it also implies one less RPC (per table).
To reproduce the error:
```sql
create table some_tbl (x int) row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde';
```

Hive: get fields from storage descriptor if available

---

client/dwh_migration_client/batch_sql_translator.py
client/dwh_migration_client/config_parser.py
client/dwh_migration_client/gcloud_auth_helper.py
client/dwh_migration_client/macro_processor.py
client/dwh_migration_client/object_mapping_parser.py

Using a double underscore for "private" methods and attributes in Python is very rare. What the double underscore actually does is mangle the name of the method or attribute during bytecode compilation to include the class name as a prefix. This makes debugging and reflection more difficult.
Instead, the convention in Python is to use a single underscore for "private" methods and attributes. Both the single and double underscore don't actually make anything private. There is no way to truly make something private in Python. In this regard, you will hear some Python people say ["We are all consenting adults."](https://python-guide-chinese.readthedocs.io/zh_CN/latest/writing/style.html#we-are-all-consenting-adults). I guess this has been revised to [responsible …

Don't use name mangling.

---

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle
dumper/app/build.gradle
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/AbstractHiveConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractRedshiftConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/JdbcPropBuilder.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/support/HiveServerSupport.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/support/HiveTestSchemaBuilder.java
dumper/app/src/test/resources/logback.xml
dumper/lib-ext-hive-metastore/build.gradle
gradle.properties

Command:
```
./gradlew :dumper:app:{cleanTest,test} --tests HiveMetadataConnectorTest -Dtest.verbose=true -Dorg.gradle.java.home=/usr/lib/jvm/java-1.8.0-openjdk-amd64
```

Hive: test dumper with an in-memory Hive metastore

---

client/config.yaml
client/dwh_migration_client/translation_type.py

Has to be done this way due to the merge conflict b/w main and alpha since alpha is protected and does not allow force pushes

Update alpha branch from main

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/RedshiftRawLogsDumpFormat.java

Dump the view `STL_QUERY_METRICS` to `querymetrics_...` in the Redshift raw logs connector when the `--assessment` flag is set.
b/241398395

Add query metrics to Redshift raw log connector

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java

Currently following examples give results which go against the documentation:
* `--assessment` is parsed as false
* `--assessment any_possible_value` is parsed as false instead of failing
As per discussion, set it to OptionSet<Void>, making any arguments after the flag noop because of joptsimple bug.

Change `--assessment` and `--metadata-stats` flags spec to Void

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java

- add STV_MV_INFO, STV_WLM_SERVICE_CLASS_CONFIG, STV_WLM_SERVICE_CLASS_STATE
- allow usage of "assessment" flag to control metadata behavior (as well as query logs)

extend redshift dump for assessment

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/RedshiftRawLogsDumpFormat.java

STL_WLM_QUERY can be big and has a timestamp, so raw logs connector is a correct place to dump it.

move STL_WLM_QUERY to raw logs connector (Redshift assessment dump)

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftEnvironmentYamlTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/RedshiftMetadataDumpFormat.java

This PR makes Redshift metadata dumper gather environment information and save them in metadata ZIP.
1. A new `redshift-environment.yaml` file will be present in the ZIP
2. `CURRENT_DATABASE()` and `VERSION()` of the Redshift instance the dumper is executed against will be stored in respectively `currentDatabase` and `redshiftVersion` attributes of the YAML.

Dump Redshift's CURRENT_DATABASE and VERSION

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractRedshiftConnector.java
dumper/app/src/main/resources/logback.xml

Add some minimal logging configuration setting root logger to `DEBUG` as a default, and allowing override with `LOG_LEVEL` environment variable. Some common packages are set at `INFO` level.
Logging of JDBC URI is now set at `TRACE` level.

Logging: add minimal configuration.

---

dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java

Source code [indicates](http://go/gh/apache/hive/blob/master/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift#L2655) that it's possible to return all the partitions for the table. 
With this I was able to get all 41K partitions for one of my tables. Tested with other smaller ones too.

Remove partitions limit from Hive Thrift metadata connector

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/DriverClasspathTest.java
dumper/app/src/test/resources/driver-classpath-test/foo/bar/DummyDriver.java
dumper/app/src/test/resources/driver-classpath-test/foo/baz/Support.java

This is needed for some JDBC drivers which provide optional features through additional JARs.

Test to confirm passing multiple JARs comma-separated to `--driver` argument allows loading classes from all of them.

---

bin/dwh-migration-dumper

Mac OS version of `readlink` doesn't support `-f`, use an all-bash alternative to resolve the paths.

Make `bin/dwh-migration-dumper` compatible with Mac OS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/TeradataLogsDumpFormat.java

`CollectTimeStamp` doesn't relate to query – from the documentation it is "A date and time unique to each buffer cache, which changes for each new buffer", also see [community answer](https://support.teradata.com/community?id=community_question&sys_id=647632d01b9010d046fcb99e0a4bcb6b).
On the Assessment side we saw 2 year difference between `CollectTimeStamp` and `StartTime` columns. This PR changes SQL WHERE clauses for query tables to use `StartTime` instead.
It doesn't touch SQL log table on purpose – `CollectTimeStamp` there represents a time when row is written to DB ([link](https://docs.teradata.com/r/Teradata-Database-Administration/April-2018/Tracking-Query-Behavior-with-Database-Query-Logging-Operational-DBAs/SQL-Log-Table-DBQLSQLTbl).

Replace CollectTimeStamp with StartTime for Teradata query tables

---

client/bqms_run/gcp/gcs.py
client/noxfile.py

`os.PathLike` is an abstract base class and subscript type arguments are not supported on ABCs until Python 3.9.
This was not caught by our `nox` tests due to a misconfiguration that was causing tests to run outside of the `nox` virtualenv. This has also been fixed.

Remove os.PathLike subscript type arg to support Python < 3.9.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java

TableSizeV contains a row per each VProc/AMP, so it can grow significantly for large dbs

aggregate results before dumping for TableSizeV in Teradata

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/JsonResponseFile.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/JsonResponseFileTest.java

Empty string in command line arguments failed with the confusing message:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException:
String index out of range: 0
```
After this change the processing is not interrupted in JsonResponseFile class, so the new error message depends on which command line option is affected by the empty string.

Fix processing empty string in command line arguments.

---

bin/dwh-migration-dumper

Gradle must be executed from the main directory of the project. Thus, the script bin/dwh-migration-dumper only works if executed from this path. To allow it being run from anywhere, use a subshell to cd to the directory and execute gradlew.

Fix gradlew path in bin/dwh-migration-dumper

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java

- add support for limitting max number of rows of DiskSpaceV table
- replace the old global options (`--max-tablesizev-rows` etc.) with the connector-specific options (`-Dteradata.metadata.TableSizeV.max-rows`)
New connector-specific options:
- for TableSizeV: `-Dteradata.metadata.TableSizeV.max-rows`
- for DiskSpaceV: `-Dteradata.metadata.DiskSpaceV.max-rows`
- for users in DatabasesV: `-Dteradata.metadata.DatabasesV.users.max-rows`
- for databases in DatabasesV: `-Dteradata.metadata.DatabasesV.dbs.max-rows`

New syntax for max number of rows parameters.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java

Add a possibility to limit the number of rows extracted from DBC.DiskSpaceV table during teradata metadata extraction.
New connector-specific options:
- for TableSizeV: `-Dteradata.metadata.tablesizev.max-rows`
- for DiskSpaceV: `-Dteradata.metadata.diskspacev.max-rows`
- for users in DatabasesV: `-Dteradata.metadata.databasesv.users.max-rows`
- for databases in DatabasesV: `-Dteradata.metadata.databasesv.dbs.max-rows`

Add connector-specific max-rows options.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/ConnectorArgumentsTest.java

Running the dumper using the command line option with the parameter containing spaces, e.g.
```
--database "A, B, C, D"
```
results in database names "A", " B", " C" and " D", which causes errors further downstream, where the database names with the spaces are not recognized.
After trimming the database names are recognized properly.

Allow spaces in database command line option.

---

README.md
client/README.md
dumper/README.md

This PR is intended to help address several problems we've seen with first-time user experience using these tools.
- Users were sometimes confused about the relationship between the tools in this repo. This PR adds a `README.md` for the dumper, which previously did not have one, and changes some wording to help clarify that these are separate tools in one repository.
- A common issue with users trying to use the dumper is that they were trying to build it themselves from source when there is no reason to and they could just be using the binary release. This PR adds a line at the top of all three `README.md` files directing the user to download the zip from the project's Releases page.
- The documentation in `client/README.md` previously did not clearly indicate the full set of …

Various improvements to first-time user documentation in READMEs

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java

The command line option `query-log-alternates` did not explain in the help output, what logTable and queryTable were. I've added the default values to make the description easier to understand.

Add defaults to query-log-alternates option help.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java

- this table can be big (60GB)
- currently it is not processed
- we can restore it when we know how to aggregate

remove SVV_DISKUSAGE dumping for Redshift

---

client/README.md

Update python client user guide about python installation in mac and windows, and mention gcloud installation as well.

update python client installation guide

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

Depending on the `assessment` flag, the default metadata and query-logs retrieval method should change.

Change default snowflake data retrieval methods.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnectorTest.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/SnowflakeMetadataDumpFormat.java

Tested manually ; sample output:
```
Timestamp,WarehouseId,WarehouseName,ClusterNumber,EventName,EventReason,EventState,UserName,RoleName,QueryId
2023-06-13 16:28:02.334,3,COMPUTE_WH,0,SUSPEND_WAREHOUSE,WAREHOUSE_AUTOSUSPEND,STARTED,,,
2023-06-13 15:57:27.169,3,COMPUTE_WH,0,RESUME_WAREHOUSE,WAREHOUSE_AUTORESUME,STARTED,,,
```

Enable dumping of warehouse_events_history for Snowflake

---

dumper/app/build.gradle
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
gradle/license-allowed.json

Support using a GCS bucket as an output target by providing an output of the form 'gs://<bucket>/<path>'.
This uses CloudStorageFileSystem to create a  instance that writs to GCS.
BUG=283484739

Support GCS as an output option

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

According to this comment https://github.com/google/dwh-migration-tools/blob/7a432471b3c1e1ef22409f375fc94d3a9824182d/dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java#L175 it only makes sense that IS is the fallback of AU, not the other way around.

Swap the order of dumping from AU vs dumping from IS.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/SnowflakeLogsDumpFormat.java

Add an extended query log dumping format including all useful information.
Also add several more light-weight fields for ordinary query log dumping format as these are essential information that is also available for other dialects
Also decouple assessment query log dumping from ordinary log dumping - assessment log dumping uses the extended query log format, while both AU- and IS- based ordinary dumpings use the original format.
Have built locally and tested against a live Snowflake database with and without --assessment flag.

Expand Snowflake query history dumping fields for assessment

---

dumper/app/build.gradle
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractConnectorExecutionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnectorTest.java

To prepare creating an alternative main class for the Cloud Extractor, split out the re-usable part into `DumpRunner` and call it from `MetadataDumper`.

Split out a dump runner out of MetadataDumper

---

client/README.md
client/examples/teradata/bteq/run.sh
client/examples/teradata/sql/run.sh

run.sh after some time leaves quite a mess in a bucket. In most cases this can be safely removed as translated artifacts are downloaded. It's up to the user if they want to keep those files or remove them and that's why we should introduce variable

add cleanup variable

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/Main.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/MainTest.java

The cloud dumper main class will be used to invoke the dumper from a GCE instance. It is intended to be invoked without arguments and get its configuratio from the instance metadata.
BUG=290102538

Implement the cloud dumper main class

---

dumper/app/build.gradle
dumper/app/src/main/sh/cloud_extractor/gce_launcher.sh

Add a shell script to be used as a launch script for GCE instances that
will download the dumper and then invoke the cloud extractor main class.
BUG=286327910

Add launch script for the cloud extractor

---

dumper/app/build.gradle
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverInformation.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverRetriever.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/Main.java
dumper/app/src/main/resources/logback.xml
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverInformationTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverRetrieverTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/MainTest.java

Integrate the JDBC `DriverRetriever` into the cloud extractor `Main`
class. If the retriever returns a `Path`, it must be propagated to
the arguments as the `--driver` parameter.
BUG=290102538

Integrate driver retriever into cloud extractor

---

dumper/app/build.gradle

The generated scripts (Windows and Unix) list each JAR individually. This creates a very classpath which is fine under Unix but generates an input line that is too long for Windows. This is discussed in https://gist.github.com/jlmelville/2bfe9277e9e2c0ff79b6
This change applies the workaround to use a wildcard (`${APP_HOME}/lib/*`). This feature was introduced in Java 6: https://docs.oracle.com/javase/6/docs/technotes/tools/windows/classpath.html
BUG=284024465

Use a simplified classpath that uses a glob

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java

The `AllTempTablesVX` view contains the database name in upper-case.

Fix dumping temp tables.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverRetriever.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/MemoizationUtil.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/util/MemoizationUtilTest.java

The cloud extractor can do multiple dumps and will likely require the same driver for all runs (e.g. metadata and logs for the same DB). Thus, the driver for it only needs to be downloaded once.

Add memoization to the driver retriever

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java

Replace the literals referencing command-line options with constants in the `toString` method.

Use constants to reference command-line options.

---

dumper/app/build.gradle

Instead of hardcoding the dumper version used by the launch script, use the version provided by `project.version` to point to the release that is currently being built.

Use the current version for the cloud launcher

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java

If the historic Teradata query logs tables are partitioned by the column of type DATE, the dumper used inefficient WHERE clause that didn't take advantage of the partitioning column. This change adds the possibility to partition by the user-specified column.

Add support for LogDate column (teradata-logs)

---

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle
dumper/app/build.gradle

Bring in explicit runtime dependencies for redshift needed for IAM credentials access. Without them, using `iam-accesskeyid` / `iam-secretaccesskey` instead of `password` fails with `ClassNotFoundException`s.
BUG=294435345

Bring in runtime dependencies for redshift

---

buildSrc/build.gradle
buildSrc/src/main/groovy/com/google/edwmigration/dumper/build/licensereport/CsvReportRenderer.groovy
dumper/app/build.gradle

The CSV license report renderer from the JK1 license plugin collects licenses for a project in a list in the following order:
1. License information from the POM files.
2. License information from manifest files.
3. Deducing the license by looking at the contents of license files.
It then uses the last entry from that list. If there is license information from a POM or metadata file, we should rather use that. The custom CSV reporter in the commit uses the first license information that it finds using the step 1 and 2, but not 3 as in that case we should rather make sure we provide the URL to the license file in the corresponding source repository.
Furthermore, it allows overriding license information for a project.

Ensure licenses are retrieved from POM/manifest

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/Main.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/MainTest.java

Add a `run(String... args)` override to allow passing in arguments directly. Also add handling of JSON response files to it.
This means that the overloaded `run` method has additional behavior beyond converting argument types which is not optimal and a result of abstraction leakage in `ConnectorArguments`. However, if we want to allow passing in arguments directly, short of a larger refactor, this is a reasonable compromise.

Add a run override to the dumper to pass in arguments

---

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle
dumper/app/build.gradle
gradle/license-allowed.json

The library java-storage-nio did not allow buckets with underscores
(https://github.com/googleapis/java-storage-nio/issues/1218). Updating
to the latest version to get the fix for this issue.
BUG=296379989

Update java-storage-nio to fix bucket name issue

---

dumper/app/build.gradle

We got asked to provide the link to the license file in the libraries source repository. This provides this information for all dependencies (as of today) where that information is not available in the POM or metadata.

Add license information

---

gradle/libs.versions.toml

The commit 1a99cef4a4e4f8828b98a93d822404ca80ae3889 to make Gradle use a version catalog accidentally downgraded the common CSV library version to 1.9.0 but the license report uses a method signature that was introduced in 1.10.0.

Bring common CSV version back up to 1.10.0

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/SummaryPrinter.java

In case of the exception that causes the dumper to fail, its stack trace is printed to the output at the end of the output before the dumper exits. Reading stack traces is easy for Java developers, but they contain too many details for the regular user, who is only interested in the error message.
I am extracting the error messages from the exception and its causal chain and printing them without the stack trace at the end of the output to make it easier for the user to see the error faster.
The original error message with stack trace is still preserved and it is printed before the final short error message.
Sample output:
```
********************************************************************
* ERROR
* Failed to initialize pool: FATAL: password authentication failed for user "joe"
* …
```

Add a shorter error at the end of the output

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java

Before:
```
10:15:31.724 [main] DEBUG com.google.edwmigration.dumper.application.dumper.MetadataDumper - Dumper wrote 9625757 bytes.
10:15:31.725 [main] DEBUG com.google.edwmigration.dumper.application.dumper.MetadataDumper - Dumper took 2.063 min.
********************************************************************
* Task Summary:
* Task SUCCEEDED (REQUIRED) Write compilerworks-format.txt containing 'teradata.dump.zip'.
...
********************************************************************
* Metadata has been saved to /path/to/dwh-migration-teradata-metadata.zip
********************************************************************
* 79 TASKS SUCCEEDED
********************************************************************
```
After:
``` …
```

Move duration and file size to summary

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaManagerConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaServicesTask.java

Adds a Cloudera connector task for dumping services and service yarn metrics. The two are combined into one task to avoid redundancy

Add Cloudera connector task for dumping services

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/SplitTextColumnQueryGenerator.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/PropertyParser.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/SplitTextColumnQueryGeneratorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/util/PropertyParserTest.java

The `RequestText` column of the `dbc.TableTextV` table may need splitting due to 64kB row size limit on Teradata 15. This change introduces a new command-line option that allows for splitting this column into multiple rows if the length is longer than the specified max length.
By default, if the option is not used the column is extracted as is, which may reach 32000 characters. With the option, the column is split into multiple rows. The max length can be any integer between 5000 and 30000 characters.
Example usage:
```
-Dteradata.metadata.max-text-length=7000
```

Add text splitting of the Teradata TableTextV table

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtils.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTaskTest.java

The `SqlTextInfo` column of the `dbc.DBQLSqlTbl` table may need splitting due to 64kB row size limit on Teradata 15. This change introduces a new command-line option that allows for splitting this column into multiple rows if the length is longer than the specified max length.
By default, if the option is not used the column is extracted as is, which may reach 31000 characters. With the option, the column is split into multiple rows. The max length can be any integer between 5000 and 30000 characters.
Example usage:
```
-Dteradata-logs.max-sql-length=7000
```

Add splitting of long SQL queries in DBQLSqlTbl

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/MetadataQueryGenerator.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtils.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/ExpressionSerializer.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/TeradataSelectBuilder.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/InExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/NaryExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/OrderBySpec.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/SelectExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/SelectSubqueryExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/SubqueryExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/SubquerySourceSpec.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/UnionExpression.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/UnionSubqueryExpression.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/MetadataQueryGeneratorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/ExpressionSerializerTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/query/model/SelectExpressionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/test/DumperTestUtils.java

Refactoring that replaces DatabasesV query generation from StringBuilder to query builder.
The change also fixes the issue with the missing `AND` operator in the `WHERE` clause.

Use query builder for DatabasesV query

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnectorTest.java

If any exception was not caught in the main thread before reaching the `main` method, it is now caught there and processed, returning exit status 1. The `System.exit(1)` invocation is moved from `MetadataDumper` class to `Main` class.
The original behavior in terms of exit status for required/optional tasks is preserved:
If any of the required tasks fail, the process returns exit status 1. Otherwise, if no required task fails, then the process returns exit status 0 (no matter if any of the optional tasks failed or not).

Return exit status 1 if extraction failed

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorRepository.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java

The `teradata-logs` connector properties were errorneously logged for all the connectors during the extraction. This logging is removed.
Additionally, a new logging is added at the beginning of processing with the detection of properties from another connector than the one currently specified and the detection of unknown properties.

Fix logging connector properties

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperUsageException.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtils.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilsTest.java

The default transaction mode in the dumper is ANSI.
The new command-line flag `-Dteradata.tmode` allows setting this mode to one of ANSI, TERA, DEFAULT or NONE for the `teradata` and `teradata-logs` connectors.

Add new flag to change Teradata Transaction mode

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnectorTest.java

1. Un-require database flag for Snowflake because it is not a necessary parameter. Still allowing providing database by the user, and will do database access check in this case.
2. Actually use the provided database to check, instead of using the wrong "current_databaase()" method.

Snowflake database flag fix

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/test/TestConnector.java

The diagnostic query generation takes a long time, while it is not necessary for unit tests. The query was executed only because of failed connections to the non-existent database, which were attempted from the real connector. Replacing the real connector with the test connector eliminates the need to connect to the real database, so the tasks are no longer failing.
The execution time decreased from 31s to 7s.
Command used for time measurement:
```
time ./gradlew cleanTest :dumper:app:test --no-build-cache
```

Speed up unit tests

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTaskTest.java

The WHERE clause generated for Teradata logs tasks (in `teradata-logs` connector without specifying the `--assessment` flag) contained repeated conditions `L.UserName <> 'DBC'`:
```
L.UserName <> 'DBC' AND L.UserName <> 'DBC' AND L.UserName <> 'DBC' AND ...
```
The `conditions` list was mistakenly modified inside the loop, which caused additional redundant conditions to be added to the query, if there was more than one time interval extracted.
If there were too many such conditions, the query failed.

Fix WHERE clause for non-assessment Teradata tasks

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/QueryLogTableNames.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/QueryLogTableNamesResolver.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtils.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/QueryLogTableNamesResolverTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilsTest.java

I'm splitting the `--query-log-alternates` option of the `teradata-logs` connector into two separate options to simplify the documentation.
Before:
```
--query-log-alternates HistoricLogTable,HistoricSqlTable
```
After:
```
-Dteradata-logs.query-logs-table=HistoricLogTable
-Dteradata-logs.sql-logs-table=HistoricSqlTable
```
This change will also align the naming of the new options with the existing options for other tables:
```
-Dteradata-logs.utility-logs-table
-Dteradata-logs.res-usage-scpu-table
-Dteradata-logs.res-usage-spma-table
```
The old option is kept for backwards compatibility.

New option for alternate query log tables

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTaskTest.java

This change fixes failing Teradata tests due to the system default timezone used in tests.

Use UTC timezone instead of systemDefault in Teradata tests

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/PropertyParser.java

Oracle metadata extraction takes extremely lot of time for some tables. It processes 5-8 records per second resulting in many hours of extraction. This is caused by extracting columns with type LONG.
useFetchSizeWithLongColumn parameter enables prefetch of rows with a LONG or LONG RAW column. It significantly reduces extraction time. (for my test instance: 10h -> 5min).
This PR enables `useFetchSizeWithLongColumn` by default. User can disable it by setting `-Doracle.useFetchSizeWithLongColumn=false` command line argument or including this property in the connection URL.

Set Oracle useFetchSizeWithLongColumn argument to true

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectTask.java

The extraction of Snowflake `QUERY_ACCELERATION_HISTORY` table is sometimes not possible, therefore I'm changing the TaskCategory from `REQUIRED` to `OPTIONAL`, so that the extraction doesn't fail in case this table is not available.
Additionally, cleanup the `TeradataJdbcSelectTask` class, because otherwise the `TeradataJdbcSelectTask` class would contain a duplicated code between it and the `JdbcSelectTask` class.

Make Snowflake QUERY_ACCELERATION_HISTORY optional

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorProperties.java

The `ConnectorArguments` class is long and it contains among others the `definitionMap` with connector properties and methods to build and access this map. I'm extracting it to a separate class to simplify the original class.

Extract connector properties from ConnectorArguments

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/DefaultArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/AbstractHiveConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HadoopSaslQopConverter.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HadoopSaslQopConverterTest.java

Additionally, move `HadoopSaslQopConverter` from `DefaultArguments` to the hive-specific package.

Add Hive QOS allowed values to help message

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java

When the view text contains a quoted string; `Table.getOriginalViewText` returns the unquoted strings. 
For example, for following view created in Hive:
```
use test;
create view `order` as select `from`, `to` from s;
```
We get following output in `tables.jsonl`.
```
{"schemaName":"test","name":"order","type":"VIRTUAL_VIEW","createTime":1709638155,"lastAccessTime":0,"owner":"root","viewText":"select from, to from s","lastDdlTime":1709638155,"retention":0,"bucketsCount":-1,"isCompressed":false,"fields":[{"name":"from","type":"string"},{"name":"to","type":"string"}],"partitionKeys":[],"partitions":[]}
```
This causes issue in view compilation, since reserved words are not quoted. Also tables are not qualified with required session schema.
Using `Table.getExpandedViewText` fixes both of …

Extract ExpandedViewText as ViewText from the Hive metastore.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/HiveMetadataDumpFormat.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Update Hive connector to extract Hive table StorageDescriptor details for SerDe and Input/Output formats. This will help in importing hive table metadata into DPMS.

[Dumper] [Hive] Extract hive table SerDe details

---

precommit.sh

Add a script to run before the commit to make sure that the correct formatting is applied, the unit tests are successful and the dist is building successfully.

Add a precommit script

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractJdbcConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/mysql/AbstractMysqlConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/netezza/NetezzaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractRedshiftConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/sqlserver/SqlServerMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/vertica/AbstractVerticaConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/io/PasswordReader.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/ConnectorArgumentsTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnectorTest.java

1. If the user requested a prompt (i.e. there's an empty `--password` flag), but Dumper can't display the prompt due to having no access to a console, then Dumper will fail. Previously, Dumper would continue with a null password.
2. `getPassword()` is now a method that never returns a null password. If no password is provided or cached, it will always prompt. The method `getPasswordIfProvided()` provides the old functionality where it may be needed.
3. Handling the prompts was separated from `ConnectorArguments` since the two aren't very closely related and to prevent `ConnectorArguments` from getting too large.
4. If a password is required, but there is no `--password` flag, then Dumper will prompt for a password. Previously, Dumper would use null as the password and continue.
5. The …

[329832604] Fix password-related NPEs in Oracle, provide more descriptive errors

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/Connector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/OracleMetadataDumpFormat.java

b/323519703
Existing Oracle XML tasks fail due to the missing argument placeholders in XML SQL query. What's more the XML metadata is retrieved sequentially for each object what makes it extremely slow. This PR fixes XML related issues and reduces extraction time:
- Replace custom XML task with regular SQL query to improve the performance. 
- Add filters for *_TABLES and *_TASKS to exclude objects not existing in DBMS_METADATA.
Extraction time was reduced from over 10h to ~25 minutes.
XML Metadata is correctly extracted for all objects.

[b/323519703] Fix Oracle XML tasks

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/MetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorScope.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtil.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorScopeTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleLogsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtilTest.java

- create a connector that will be used to collect `oracle-stats` data
- add an enum to represent the connector type (`logs`, `metadata` or `stats`) and use it in Oracle
- add tests verifying Oracle connector type information in output filenames and help text

[b/337839892] Create an empty oracle-stats connector

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorScope.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQuery.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractJdbcTask.java
dumper/app/src/main/resources/oracle-stats/metadata/app-schemas-summary.sql

b/341297017
- Add the summary version of app_schemas.sql from DMA
- Add a version of newCsvResultSetExtractor in AbstractJdbcTask that avoids the '-1' dummy value
- Add a JdbcTask class for oracle-stats
- Use StatsJdbcTask to avoid printing entire SQLs for each query
- Use a simpler CSV format logic for StatsJdbcTask
- Add a check and change annotations to improve null handling in StatsJdbcTask

[b/341297017] Integrate the summary version of app_schemas.sql from the DMA tool

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java

Remove `TeradataLogsConnectorTest::testConnectorSynthetic`.
This test is skipped by all test runs that don't have the correct option enabled (including testing by CI).
It's unfinished (ends in TODO, has no assertions) and about 50 lines of its code are inside an `if (false) {` block.
It has been that way since this repository was created, I think the best course of action now is to remove it.
Should some part of it turn out to be useful later on, we'll still be able to restore it from git history.

[code health] Remove testConnectorSynthetic

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/MetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/generic/GenericConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorScope.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtil.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/generic/GenericConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorScopeTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtilTest.java

b/275708841
- fix all cases of duplicate "-logs" suffixes
- add tests to verify that output names in the generic connector remained correct
```
* bigquery-logs - dwh-migration-bigquery-logs.zip
* generic - dwh-migration-generic-logs.zip
* oracle-logs - dwh-migration-oracle-logs.zip
* redshift-logs - dwh-migration-redshift-logs.zip
* redshift-raw-logs - dwh-migration-redshift-raw-logs.zip
* snowflake-account-usage-logs - dwh-migration-snowflake-account-usage-logs.zip
* snowflake-information-schema-logs - dwh-migration-snowflake-information-schema-logs.zip
* snowflake-logs - dwh-migration-snowflake-logs.zip
* teradata14-logs - dwh-migration-teradata14-logs.zip
* teradata-logs - dwh-migration-teradata-logs.zip
* vertica-logs - dwh-migration-vertica-logs.zip
```

[b/275708841] Fix duplicate "-logs" suffix in some output archive names

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/Connector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/MetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/DriverClasspathTest.java

b/342534698
- add missing oracle-stats summary
- enable summaries for all connectors, not just logs and metadata
- allow connectors to override summaries
- separate connector summary from MetadataDumper logic

[b/342534698] fix: missing summary after oracle-stats completes

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/JsonResponseFile.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractJdbcConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/bigquery/BigQueryLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/bigquery/BigQueryMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilityLogsJdbcTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractConnectorExecutionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnectorExecutionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnectorTest.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/utils/PartitionNameGenerator.java
dumper/lib-ext-hive-metastore/src/test/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClientTest.java
dumper/lib-ext-hive-metastore/src/test/java/com/google/edwmigration/dumper/ext/hive/metastore/utils/PartitionNameGeneratorTest.java

- String is final, so `? extends String` is not needed.
- Predicates work directly on Strings, so `? super String` is also not needed.
- small fix of logging placeholder and checking string emptiness in `PartitionNameGenerator`

Cleanup of redundant generics for String

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java

Catalogs are saved to the JSONL file, obtained by the conversion of each of the catalogs received from Thrift message directly to JSON.

[b/343037983] Extract catalogs from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java

Extract all the fields from the databases and save the result in the new `databases.jsonl` file that contains a JSON serialization of the Thrift response.

[b/343047614] Extract databases from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/AbstractHiveConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java

Do not extract migration metadata by default, so that the discovery for assessment can be used without additional metadata required by migration.
For migration case require the `-Dhiveql.migration.metadata=true` flag.

[b/343047614] Hide migration metadata extraction behind a flag

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java

unzip output:
```
Archive:  dwh-migration-oracle-stats.zip
inflating: compilerworks-version.txt  
inflating: compilerworks-arguments.txt  
inflating: compilerworks-metadata.yaml  
inflating: db-features.csv         
inflating: db-instances.csv        
inflating: pdbs-info.csv           
inflating: app-schemas-pdbs.csv    
inflating: app-schemas-summary.csv  
inflating: hist-cmd-types.csv
```

[b/343187503] Change output paths to avoid subdirectories

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java

I'm renaming the parameter to follow the convention used in other task classes.

Rename name to targetPath in StatsJdbcTask

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java

Add the file compilerworks-format.txt to oracle-logs and -stats outputs
The contents of the files are simply:
```
oracle.logs.zip
```
```
oracle.stats.zip
```

[b/343862780] add a compilerworks-format text file in oracle-logs and -stats output

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilityLogsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectIntervalTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectTask.java
dumper/lib-common/src/main/java/com/google/edwmigration/dumper/plugin/ext/jdk/progress/RecordProgressMonitor.java

The method newCsvResultSetExtractor in AbstractJdbcTask takes a special value of count=-1 to indicate that `count` is not provided. A version of the same method with no `count` parameter was added earlier.
- instead of passing count=-1, use the method with no 'count' parameter
- disallow negative values of 'count' in the future

Remove the special handling of count=-1 in newCsvRSE

---

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle
dumper/app/build.gradle

Add a Gradle task that generates coverage report for the Dumper app by running:
```
./gradlew dumper:app:jacocoTestReport
```
The task is optional and not included in any tests.
The generated reports are HTML and appear in `dumper/app/build/reports/jacocoHtml`.

Add an optional Jacoco report task in Gradle

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Extract tables in the new format to the `tables-raw.jsonl` file.
The file contains the JSON serialization of the raw response from Hive Metastore API, each table on a separate line.

[b/343069385] Extract tables from HMS

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/DriverClasspathTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/DriverInformationTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnectorExecutionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtilTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/MemoizationUtilTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/OptionalUtilsTest.java

The annotation `@RunWith(JUnit4.class)` was missing on a few classes. It doesn't affect test execution, but I'm adding it for consistency.

Add RunWith JUnit4 annotation

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Extracted foreign keys are added to the existing file `tables-raw.jsonl` as a new field `foreignKeys`.

[b/343069385] Extract foreign keys from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Extracted unique, non-null, default and check constraints are added to the existing file `tables-raw.jsonl` as new fields: `uniqueConstraints`, `nonNullConstraints`, `defaultConstraints` and `checkConstraints`.

[b/343069385] Extract constraints from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Extracted table statistics are added to the existing file `tables-raw.jsonl` as a new field `tableStatistics`.

[b/343069385] Extract table statistics from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java

Extract partitions in the new format to the `partitions.jsonl` file.
The file contains the JSON serialization of the raw response from Hive Metastore API, partitions for each table on a separate line.

[b/343063007] Extract partitions from HMS

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/TaskSetState.java

TaskSetState has a synchronization mechanism, which intends to provide mutual exclusion when accessing the private `resultMap`. However, the public method:
```
getTaskResultMap()
```
returns `resultMap` to the caller, which makes such synchronization ineffective, as the caller is able to read and write to this map freely.
The primary goal of this PR is to replace this approach with methods that have correct synchronization.
- replace getTaskResultMap with safe methods
- add classes representing return types needed by the new methods
- in the newly added methods, discourage accessing them directly from `Impl`
- inline a redundant method, remove unchecked cast
- fix a variable name referring to "tasksNotSucceeded", when it actually represents only the tasks that ended in failure
- remove …

Address concurrency issues in TaskSetState

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/ArgumentsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/FormatTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/VersionTask.java

b/345177751
The classes ArgumentsTask, FormatTask and VersionTask will continue to be used. Remove the @.Deprecated annotation from these classes

[b/345177751] Revert the deprecation of translation file tasks

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java

Although the SQLs with scripts for oracle-stats are included in the JAR, there is no verification that they were added correctly. Until the application is run, there will be no symptoms of a missing SQL file, incorrect name or a file being in the wrong folder.
This PR aims to mitigate this issue by adding a configuration check in Junit. The new test will attempt to load all native-sourced files in the stats task list and lists all file names for which loading has failed.

Add a basic check for oracle-stats SQLs

---

dumper/app/build.gradle
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/BashTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScripts.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScriptsTest.java
gradle/libs.versions.toml

Create a temporary directory in the current working directory to extract the scripts.
Remove the Apache commons-exec dependency.

[b/341097448] Use temporary directory for extracting scripts

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java

In the method `buildSelectStarTask`, the parameters and variables prefixed with `dba_` actually refer to tables prefixed with `all_` and vice versa.
Fix this by renaming the parameters to match their actual values.

Fix: Parameter names don't match their values

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQuery.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/resources/oracle-stats/awr/hist-cmd-types-awr.sql
dumper/app/src/main/resources/oracle-stats/awr/source-conn-latest.sql
dumper/app/src/main/resources/oracle-stats/awr/sql-stats-awr.sql
dumper/app/src/main/resources/oracle-stats/statspack/hist-cmd-types-statspack.sql
dumper/app/src/main/resources/oracle-stats/statspack/sql-stats-statspack.sql
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQueryTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java

The user can optionally provide the number of days for query logs, similarly to existing logs-type connectors.
The end of the timeframe will be the present time, the start will be the present time minus the provided number of days.
The number of days can be a value from the inclusive range [1, 10000]

[b/352469141] Make oracle-stats duration customizable

---

dumper/lib-common/src/test/java/com/google/edwmigration/dumper/plugin/ext/jdk/progress/RecordProgressMonitorTest.java

`testSlow` sleeps for a total of about 50 hours. It has been disabled since the migration to GitHub. The behavior it tests is already tested in testFast, although with fewer iterations (10^6 instead of 10^7).

Remove an ignored test in RecordProgressMonitor

---

dumper/app/src/main/resources/oracle-stats/statspack/hist-cmd-types-statspack.sql
dumper/app/src/main/resources/oracle-stats/statspack/sql-stats-statspack.sql

- refer to averages instead of sums to match AWR
- use a consistent header naming convention

[b/352469802] Update the Statspack SQLs to match changes in AWR queries

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/Connector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/MetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsPermissionExtractionConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/TaskSetState.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/DriverClasspathTest.java

I'm moving the most important details about the dumper execution to the last 3 lines of the summary printed at the end of the dumper execution.
Before:
```
********************************************************************
* Dumper wrote 44010458 bytes.
* Dumper took 5.056 min.
********************************************************************
* Task Summary:
* Task SUCCEEDED (INFORMATIONAL) Write compilerworks-version.txt from product version information.
* Task SUCCEEDED (REQUIRED) Write compilerworks-format.txt containing 'teradata.logs.zip'.
* Task SUCCEEDED (REQUIRED) Write utility_logs_2024-03-14T00:00:00Z.csv ...
* ...
********************************************************************
* Logs have been saved to /home/joe/dwh-migration-teradata-logs-20240717T143924.zip …
```

Summary cleanup

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQuery.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQueryTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java

[oracle-stats connector]
The `IOException` thrown by a method in `common.io.Resources` is due to a general-purpose `read` method used by the implementation.
As the [documentation](https://docs.oracle.com/javase/8/docs/api/java/io/IOException.html) shows, the exception is very broad, covering various issues related to permissions, hosts, sockets, interrupts and other topics.
Oracle-stats uses `Resources` only to load SQLs included in the JAR. Almost all subclasses of IOException are inapplicable to this use case. The only issues with these files that we see somewhat frequently are:
- file is missing
- provided path to the file is incorrect
Neither  of these results in an IOException, because `Resources` will throw `IllegalArgumentException` before getting to the stage where an …

Wrap IOException for oracle-stats SQL resources

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQuery.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/QueryGroup.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQueryTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java

Unlike the SQL text itself or query parameters, some properties are common for all SQLs in a single subdirectory.
Group these properties into a new class, decreasing the number of properties accessed directly from OracleStatsQuery.
- create QueryGroup as a value-based class
- move stats-source, tenant-setup and required-ness properties to the new class

Group together the attributes related to SQL scripts subdirectories

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java

The `compilerworks-metadata.yaml` contains the command-line options printed in the format that is serialized from Java internal model. For the `--output` option it was:
```
output=Optional[/home/joe/sample-extraction]
```
or if the option was not specified:
```
output=Optional.empty
```
After the change, the value is serialized:
```
output=/home/joe/sample-extraction
```
or
```
output=null
```

Fix output dir format in metadata yaml

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/QueryGroup.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/task/NoResultTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/task/ResultMessageTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/task/VoidTask.java

The task of determining if a given SQL group was successful is complicated from the user's perspective.
For example, if they want to determine whether CDBs AWR data will be available in the archive, they need to:
- go through the list of all task statuses
- find the ones which refer to CDBs and have AWR as their statsSource
- ensure that the status is either SUCCEEDED or SKIPPED for each task
Use existing Dumper mechanisms to simplify this process. Provide a summary for each group so that after successful extraction of data from an entire SQL group, an informational message will be printed, e.g:
```
* Task SUCCEEDED (OPTIONAL) Load AWR data (cdb version).
```
This is similar to what's done in OracleMetadataConnector, with two differences: the message is also shown on success and its …

Add a summary success message for each stats SQL group

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScripts.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopMetadataConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScriptsTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/ScriptTmpDirCleanup.java

The temporary directory is created for bash scripts during test execution. It should be deleted after tests, because otherwise such directories start to pile up, if the tests are executed multiple times during development.

[b/355392538] Delete script tmp directory after tests

---

dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/OracleMetadataDumpFormat.java

Correct a mistake in the code where the wrong column name (`OWNER`) was used to retrieve sequence information via `XmlSequences` from an Oracle database. The correct column name is `SEQUENCE_OWNER`, as documented in the Oracle reference (https://docs.oracle.com/en/database/oracle/oracle-database/23/refrn/ALL_SEQUENCES.html). A new enum value `SEQUENCE_OWNER` has been added, and the old `OWNER` value is now marked as deprecated.

[b/350521386] Add correct Oracle column name for ALL_SEQUENCES.SEQUENCE_OWNER

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/resources/oracle-stats/cdb/awr/sys-metric-history.sql
dumper/app/src/main/resources/oracle-stats/cdb/native/cell-config.sql
dumper/app/src/main/resources/oracle-stats/cdb/native/data-files.sql
dumper/app/src/main/resources/oracle-stats/cdb/native/osstat.sql
dumper/app/src/main/resources/oracle-stats/dba/awr/sys-metric-history.sql
dumper/app/src/main/resources/oracle-stats/dba/native/cell-config.sql
dumper/app/src/main/resources/oracle-stats/dba/native/data-files.sql
dumper/app/src/main/resources/oracle-stats/dba/native/osstat.sql

This PR introduces 4 additional SQL to extract Oracle system configuration:
- osstat - General system statistics. Required to collect CPU configuration.
- cell-config - Information about Exadata storage cells. This view exists for non Exadata systems, but data is missing.
- data-files - Information about Oracle data files that will be used to calculate physical storage size.
- sys-metric-history - History of system metrics like CPU usage.

[b/359866106] Add SQLs to discover Oracle exadata and system configuration

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java
dumper/app/src/main/resources/oracle-stats/cdb/awr/segment-stats.sql
dumper/app/src/main/resources/oracle-stats/dba/awr/segment-stats.sql

Data extracted from cdb/dba_hist_seg_stat views includes segment level statistics that can be used to better understand database storage trends.

[b/361012673] Extract historical metrics from Oracle cdb_hist_seg_stat view

---

bin/dwh-migration-client
build.gradle

I'm removing the `dwh-migration-client`, because it seems unused.

Remove dwh-migration-client

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/BashTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScripts.java
dumper/app/src/main/resources/hadoop-scripts/ip-address.sh
dumper/app/src/main/resources/hadoop-scripts/ls-usr-local-lib.sh
dumper/app/src/main/resources/hadoop-scripts/ls-var-log.sh
dumper/app/src/main/resources/hadoop-scripts/os-release.sh
dumper/app/src/main/resources/hadoop-scripts/single-line-scripts.json
dumper/app/src/main/resources/hadoop-scripts/single-line-scripts.txt
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopScriptsTest.java

Some of the bash scripts are short enough to fit in a single line. It will be easier to add new scripts if they are grouped in a single JSON file. Besides that, they work the same as the other scripts saved in individual files, i.e. they are executed as separate bash scripts and they produce the same format of the output.

Group single-line scripts in a single text file

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/AbstractHiveConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java

The flag was added only temporarily for testing the new format of the hive dump. It is no longer needed.

[b/356467392] Remove MIGRATION_METADATA flag

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsStatusReportTask.java

Make the extraction of slow nodes in `HdfsStatusReportTask` more resilient by catching the exception and letting the rest of the extraction to continue.
Additionally, make the task optional.

[b/353201454] Ignore slow nodes extraction failure

---

dumper/app/src/main/resources/oracle-stats/cdb/awr/source-conn-latest.sql
dumper/app/src/main/resources/oracle-stats/dba/awr/source-conn-latest.sql

This PR adds following columns to the `source-conn-latest` SQL file:
- ConId
- SqlId
- ReadIoBytesTotal
- WriteIoBytesTotal
- ReadIoRequestsTotal
- WriteIoRequestsTotal
- CpuTimeTotal
It also changes the snapshots table to `_hist_ash_snapshot` as recommended by Oracle documentation.

[b/362205662] Extend Oracle source-conn-latest sql with additional columns

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsExtractionConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/meta/AbstractMetaConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/DumpMetadataTask.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/CoreMetadataDumpFormat.java

This PR adds the `connectors` attribute in the `compilerworks-metadata.yaml` file:
```
connectors:
- "cloudera-metadata"
- "hiveql"
- "hdfs"
```
The sample of the whole file with the new `connectors` attribute (irrelevant parts omitted):
```
format: "cloudera.zip"
timestamp: 1724795274133
product:
version: |
API Common:2.34.0
...
arguments: "ConnectorArguments{connector=cloudera, ...}"
connectors:
- "cloudera-metadata"
- "hiveql"
- "hdfs"
```

[b/352490642] Add child connectors to metadata yaml

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsExtractionConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsExtractionTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsHandle.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/SingleDirScanJob.java

As per convention, the logger is instantiated in the class it is used in (with rare exceptions like progress logger).
Also, use placeholder instead of string concatenation in logger.

Cleanup loggers in HDFS connector

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractJdbcTask.java

If there is an object in the ResultSet, for which `toString` returns null, the task involving the object may fail, depending on the specific class of this object.
In all cases where a ResultSet element object's `toString` would return null, replace the object with null, which will be written as an empty csv item without error.

[b/364035944] Prevent a NullPointerException where a result's toString has returned null

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/ParallelTaskGroup.java

- use the correct ExecutorManager method, rather than suppressing a warning
- remove a comment with incorrect information about ParallelTaskGroup being used only for Redshift (it is also used for Greenplum)
- (x2) replace `throws Exception` with a more precise declaration
- remove redundant extension of `Callable`
- remove redundant generics
- add missing annotations

ParallelTaskGroup fixes

---

dumper/app/src/main/resources/oracle-stats/cdb/native/db-link-sources.sql
dumper/app/src/main/resources/oracle-stats/dba/native/db-link-sources.sql

Rename a column in oracle-stats SQLs for consistency

[b/370428253] Rename 'Dbid' to 'DbId'

---

.gitignore
dumper/app/.gitignore
dumper/lib-common/.gitignore
dumper/lib-dumper-spi/.gitignore
dumper/lib-ext-bigquery/.gitignore
dumper/lib-ext-hive-metastore/.gitignore

This prevents them from appearing in git as unstaged changes
New files in e.g. the groovy scripts for license now don't need to be force added.

More precise .gitignore rules

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

The LogsConnector and MetadataConnector classes have no effect when provided to the AutoService annotation. Keep the necessary Connector class and remove others from AutoService annotations for all Snowflake connectors.

Remove redundant arguments from AutoService in Snowflake

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataQueryLogsJdbcTask.java

Logging first and last query log entry for Teradata.
For this purpose created new separate task `TeradataQueryLogsJdbcTask`.
This is output of the task with query log dates:

Output first and last query log entries for Teradata with a new task

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInput.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

- Replace method overrides with an enum parameter
- Remove misused `ForOverride` annotation
- Reduce visibility of class members
- Subclasses shouldn't override `addTasksTo` - prevent this with `final`

Clean up class design for Snowflake Metadata

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractJdbcConnector.java

The error message before:
```
java.sql.SQLException: Failed to load or instantiate null from []: java.lang.IllegalArgumentException: File does not exist: '/Users/vsidorovich/github/dwh-migration-tools/dwh-runs'
at com.google.edwmigration.dumper.application.dumper.connector.AbstractJdbcConnector.newDriver(AbstractJdbcConnector.java:155)
at com.google.edwmigration.dumper.application.dumper.connector.teradata.AbstractTeradataConnector.open(AbstractTeradataConnector.java:204)
at com.google.edwmigration.dumper.application.dumper.MetadataDumper.run(MetadataDumper.java:179)
at com.google.edwmigration.dumper.application.dumper.MetadataDumper.run(MetadataDumper.java:90)
at com.google.edwmigration.dumper.application.dumper.MetadataDumper.run(MetadataDumper.java:67)
at …
```

[issue 114] improve error messages for JDBC driver

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtil.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/ArchiveNameUtilTest.java

Update `redshift-raw-logs`, `teradata-logs` and `snowflake-logs` connectors to use "yyyy-MM-dd'T'HHmmss'Z'" pattern instead of default `ISO_OFFSET_DATE_TIME`. This format was already used for Redshift `cluster_usage_metrics_`, but not applied for all the other files.
The timestamp suffix is added to each time based file generated by the dumper. Currently we use the `ISO_OFFSET_DATE_TIME` format that includes colon characters. Windows file system does not accept colons in the file names what results in following exception:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 21: ddltext_2024-10-09T14:00:00Z.csv
```

[b/373568138] Change timestamp format used in zip entry files to work on windows

---

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalIterableTest.java

- The variable `durationOfHour` stores the duration of a day, fix it to store the duration of an hour
- Despite the above, tests didn't fail, because `hourExpander` was also configured to expand to days, not hours - fix this as well
- A constant of 168 **days** is introduced without explanation. A week has 168 **hours**. I'm assuming it's supposed to be 1 week as in the assertion that comes after and the arguments were incorrect as in the assertions before. Fix it by using the duration and expander which refer to hours, not days.
- Remove the `Nonnegative` annotation applied to an `Iterable` parameter. `Iterable`'s don't have a sign.
- Extract tested values to named variables to document their meaning

Fix bugs in ZonedIntervalIterableTest

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java

Create a new connector based on SnowflakeMetadataConnector and make it extract the subset of SF TCO Lite data which consists of metadata only.
This is done by duplicating code of SnowflakeMetadataConnector. As agreed, the implementation will change later to share common abstractions.

[b/375140671] Create a new connector for SF TCO Lite

---

dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java
dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java

Error caused by an already [known issue when reading Hive columns](https://github.com/google/dwh-migration-tools/blob/409b87cb7c6182afa4180c56cd93e524fc0f84d3/dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java#L306): "Storage schema reading not supported"

[b/374026408] Fix Hive extraction for Iceberg raw tables

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInformationSchemaMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeInput.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

This is a similar change to https://github.com/google/dwh-migration-tools/pull/586 but for the `snowflake-logs` connector.
Limit visibility and overriding of `SnowflakeLogsConnector`, replace unnecessary overrides with constructor parameters.

Class design cleanup for Snowflake Logs

---

.github/dependabot.yml

Run once a week on Monday morning to reduce `noise`.
Upadte logback only `1.3.x` for JDK 8 compatibility.

[improve] Configure dependabot

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java

Add a new task and query to the Snowflake (TCO) Lite connector that accesses the `WAREHOUSE_EVENTS_HISTORY` view in the `ACCOUNT_USAGE_SCHEMA` and lists the columns:
- event_name
- cluster_number
-  warehouse_id
- warehouse_name
counting the occurences of each combination.

[b/377253441] Add a task to get aggregate events in snowflake-lite

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsHandle.java

Dumper/HdfsConnector now takes two more (optional) args, that should always go together:
--kerberos-principal _service-principal_
--kerberos-keytab-path _path-to-keytab-file_

Enable Kerberos keytab auth for HdfsConnector

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsHandle.java

Streamlined the Kerberos auth for Hadoop and its possible options/configuration.
This will require thorough description in the docs/user manual:
--hadoop-core-site-xml [String]      Path to Hadoop's core-site.xml (when using Kerberos auth).
(default: /etc/hadoop/conf.cloudera.hdfs/core-site.xml)
--hadoop-hdfs-site-xml [String]      Path to Hadoop's hdfs-site.xml (when using Kerberos auth).
(default: /etc/hadoop/conf.cloudera.hdfs/hdfs-site.xml)
--hadoop-rpc-protection <String>   Protection of Hadoop rpc calls (when using Kerberos auth)
Options are: authentication, privacy, integrity.
--hdfs-principal-prefix <String>      HDFS node(s) principal prefix (when using Kerberos auth)
(default: hdfs/_HOST@)
--kerberos-auth-for-hadoop            Use Kerberos auth for Hadoop.
--kerberos-keytab-path …

[b/381361432] hdfs connector may use kinit-cached credentials for auth

---

dumper/lib-ext-hive-metastore/build.gradle
dumper/lib-ext-hive-metastore/gradle.lockfile

Beside security vulnerabilities in `log4j`,  we use `slf4j` with `logback`, so all `log4j` implementation deps must be excluded.

[b360554196] remove log4j implementation

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTaskTest.java

The API response is an array of https://archive.cloudera.com/cm7/7.11.3.0/generic/jar/cm_api/apidocs/json_ApiComponentInfo.html 
For example:
```
[
{
"cdhVersion": "CDH7",
"cdhRelease": "CDH 7.2.18-1.cdh7.2.18.p400.57851273",
"componentVersion": "3.1.1.7.2.18.400-40",
"componentRelease": "57851273",
"componentInfoSource": "PARCEL",
"isActive": true,
"componentConfig": null,
"name": "hadoop-kms"
},
{
"cdhVersion": "CDH7",
"cdhRelease": "CDH 7.2.18-1.cdh7.2.18.p400.57851273",
"componentVersion": "3.1.3000.7.2.18.400-40",
"componentRelease": "57851273",
"componentInfoSource": "PARCEL",
"isActive": true,
"componentConfig": null,
"name": "hive"
},
...
]
```
So, we will lose the information about the `host` on server. To avoid it, I wrap the response into custom data structure.

[b/380000872] Add hostId to jsonl

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractAwsApiTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftClusterNodesTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftClusterUsageMetricsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftClusterUsageMetricsTaskTest.java

- remove `writeRecordsCsv` which worked on lists of a file's all records
- create `CsvRecordWriter` for writing records one at a time
- replace `Optional` with `Nullable` to simplify a helper method
- move the list of extracted cluster usage metric types to `RedshiftClusterUsageMetricsTask`
- refactor record formatting in `RedshiftClusterUsageMetricsTask`
We use a list of types of metrics in this connector. The refactor of the usage metrics task relies on that list being a constant. After merging this change, we still can introduce more metric types, but creating custom types of metrics dynamically would require a different approach.
Note that despite working on the same code, this PR does not aim to fix b/382467945.

Remove writeRecordsCsv, refactor the usage metrics task for Redshift

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/handle/HandleUtil.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/handle/JdbcHandle.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/handle/HandleUtilTest.java

JdbcHandle is a class which provides common Jdbc logic to connectors that choose to use it as their handle.
Redshift extraction needs (and currently uses) the general-purpose logic from JdbcHandle, but it also needs to define its own handle, for aws-specific connection setup (at the moment this setup is done in Tasks).
Make the JdbcHandle methods available as a util class so that a custom handle planned for Redshift will be able to use them.

[b/382467945] Move parts of JdbcHandle logic to a util class

---

.github/dependabot.yml

Dependabot wasn't run successfully for some period of time https://github.com/google/dwh-migration-tools/network/updates/17324861/jobs
Logs are not available, so checking the latest changes.

remove ignore section for dependabot

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/handle/JdbcHandle.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/test/TestConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/task/AbstractTaskTest.java

Similar to #680, but no changes to AbstractHandle.
This avoids the need for `super.close()` in JdbcHandle
Given that the value represented by DummyHandle isn't important in the tests, a Handle from lambda is simpler, with the same effect and maintainability.

Remove DummyHandle, don't extend AbstractHandle in JdbcHandle

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractRedshiftConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftUrlUtil.java

- Postgres URL builder
- Simple RS URL builder
- Redshift IAM URL builder
- default port constant
- move commented-out code to a method
- remove redundant comments
- remove an unused method
- remove redundant `SuppressWarnings`
The moved code represented an additional responsibility of the Redshift connector besides managing the handle in `open` and building the task list in `addTasksTo`. Simplify the class to make working on its main features easier.

[b/387249832] Move Redshift URL utilities to a Util class

---

.github/dependabot.yml

Dependabot works again, returning config by lines to localize an error.

[OPS] Update dependabot config

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaManagerTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaTimeSeriesTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostRAMChartTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaServicesTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaManagerTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostRAMChartTaskTest.java

- Move objectMapper under the API methods of AbstractClouderaManagerTask.
- Add tests to cover different Cloudera http responses during the tasks.

[b/385081594]: Add more http tests for Cloudera tasks

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java

- Add missing extraction of `PROCEDURES`
- Add missing extraction of `WAREHOUSE_METERING_HISTORY`
- Move extraction of `DATABASES`, `SCHEMATA`, `TABLES` to another class
[dry-run output with queries](https://github.com/user-attachments/files/18537243/dry-run.txt)

[b/392580006] fix: Missing views in SF Lite extraction

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaYarnApplicationTypeTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaYarnApplicationTypeTaskTest.java

It's possible to have a collision between the same application IDs in context of different clusters.

Fix: Collect cluster name with YARN application types

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ranger/RangerConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ranger/RangerConnectorTasksTest.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/RangerDumpFormat.java

HDFS assessment job cannot work without compilerworks_metadata.yaml, so there was a need to add it.
Testing:
There was a problem with automatic testing, for test solution should be create integration/e2e test that checks if HDFS assessment is passing. There is no point of unit testing it - DumpMetadataTask was tested in different place, adding files to folder too. And there is no point of testing logic of totally different component. 
I checked HDFS assessment before and after and fix works as it shows assessment job lszydelko-test-12.

[b394751887] add compilerworks_metadata.yaml to Ranger output zip

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractJdbcConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/airflow/AirflowConnector.java

Airflow may work with different databases, so the airflow connector check different driver classes. Do not find some driver class for example  PostgreSql is expected if the instance of Airflow works with MySql.
Errors and stack traces in the output may be confusing for user, so improve it.
before:
```
10:43:20.610 [main] WARN  com.google.edwmigration.dumper.application.dumper.connector.AbstractJdbcConnector - Cannot load driver class [com.mysql.jdbc.Driver] from path [/Users/vsidorovich/jdbc/postgresql-42.7.5.jar]: {}
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
at java.lang.Class.forName0(Native Method) …
```

[b/390590500] use info log level for not found drivers for Airflow connector

---

dbsync/build.gradle
gradle/license-allowed.json

This PR adds a licenseReport task to the dbsync module. As a result `./gradlew checkLicense` command will produce additional licenses file for the `dbsync` module. 
Report path: dbsync/build/reports/dependency-license/licenses.csv

Add licenseReport task to dbsync

---

build.gradle

This PR adds additional `checkLicense` task in the repository root to generate single licenses.csv file with all the dependencies.
File will be stored in `build/reports/dependency-license/licenses.csv`

Add task to build the license report for the whole dwh-migration-tools repository

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java

Create a csv to match b/402429275 containing the metering history.
The new file is called warehouse_metering_lite, it's based on the previous warehouse metering task which was removed.

[b/402436948] Create a lite version of WarehouseMeteringHistory

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaTimeSeriesTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostRAMChartTask.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerHandle.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaTimeSeriesTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostRAMChartTaskTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerConnectorTest.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/CoreMetadataDumpFormat.java

Some of the tasks where optional by design but wasn't marked as optional in the implementation.

[OPS] Mark some Cloudera tasks optional

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java

The flag is needed to enable Assessment features for connectors that don't support it by default.
The `snowflake-lite` connector is built for Assessment. In this case the flag is never needed so it shouldn't be supported.

[b/394577286] Disallow the --assessment flag for snowflake-lite

---

build.gradle
dumper/app/build.gradle
gradle/libs.versions.toml

All tests slower than `2` (configurable) seconds will print execution time to console. So, we will continuously observer test performance.
For example it was obvious that `connector.hive.HiveMetadataConnectorTest` test is very slow. Now we can see that it spend `2+` minutes and ~`30` seconds for all the rest tests.
```
Test testLoadedHive312 PASSED (2m 14s)
...
SUCCESS: Executed 354 tests in 2m 25s (9 skipped)
```

[OPS] add plugin to log test execution time into console

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/HeaderTransformerUtil.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/MetadataView.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnectorTest.java
dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/SnowflakeMetadataDumpFormat.java

Also fixes some issues with the `USE DATABASE` statement and some qualification issues for the `INFORMATION_SCHEMA` queries.

[b/394312229] Dump Snowflake external table metadata without the assessment flag

---

dumper/app/build.gradle
dumper/app/gradle.lockfile
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnectorTest.java
gradle/libs.versions.toml

This PR enables an optional snowflake MFA caching mechanism. This simplifies the usage of the dumper for the users who decide to use the user&password auth flow with the MFA. This allows user to approve MFA request only once instead of receiving the push notification on every single SQL query.
This requires setting the `authenticator` property to `username_password_mfa` and adding JNA classes to the classpath. Changing the `authenticator` property does not affect the authentication if MFA is disabled for the user.

[b/404819770] Enable snowflake MFA caching

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/greenplum/GreenplumLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/ParallelTaskGroup.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/TaskGroup.java

Add the builder as discussed in 1:1 and remove the `TaskGroup#addTask` method.
This is step 1 of 2 to make the parallel task list immutable.

Add a builder for ParallelTaskGroup

---

dumper/app/build.gradle

The source code of our dependencies must be included into distributed zip file. It's requirement some licenses of our dependencies. (for example CDDL).

[OPS] add source code to distribution

---

dbsync/README.md
dbsync/common/src/test/java/com/google/edwmigration/dbsync/jdbc/JdbcByteSourceTest.java
dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GcsyncClient.java
dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GenerateCheckSumMain.java
dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/ReconstructFilesMain.java
dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/Util.java
dbsync/storage-gcs/src/main/java/com/google/edwmigration/dbsync/storage/gcs/GcsStorage.java

This would be helpful if we are syncing a large number of files. The change implement the following feature.
1. Write the md5 of the file on gcs as a header while generating checksums. Skip generating if a checksum file exists and the md5 of the file on gcs hasn't changed.
2.Write the md5 of the file on source as a header while generating instructions,. skip generating it again if the instruction file exists and the md5 hasn't changed.
3. Before replacing the file on gcs with the reconstructed file, make sure that the md5 matches with the source to avoid potential corruption.

Allow the tool to reuse existing progress resuming from a crash.

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java

Set default `username_password_mfa` authenticator option only if the custom URL is not provided by the user. This allows overriding it with custom value like 'externalbrowser'.
Additionally, we skip asking about the password if `--password` flag is not provided to allow using passwordless auth options.

Allow overriding snowflake authenticator parameter

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java

Currently `deleted` column is filtering by checking if it is `null` or not.
This is not correct, as `deleted` column has `boolean` type, should be checked by comparing with `false`.
Doc: https://docs.snowflake.com/en/sql-reference/account-usage/table_storage_metrics

Fixing predice for tables_storage_metrics csv in SF Lite

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java

The flag has no effect, because all Lite queries are prefixed with the `SNOWFLAKE` database.
It was added automatically to all Snowflake connectors.
Remove the flag for Lite, keep it for Logs and Metadata. The flag remains allowed to keep backwards compatibility.

[b/418155474] Drop the --database flag from snowflake-lite

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java

Removing creating csv with clusters spin on and spin off. This logic is already done inside materialized view.
And there is no ingestion logic for these files.

Clean unused csv in SF Lite

---

buildSrc/src/main/groovy/com/google/edwmigration/dumper/build/licensereport/OverridesUtil.groovy

Add missing license URLs for `net.java.dev.jna:jna-platform` and `net.harawata:appdirs`.

Add missing license URLs

---

build.gradle

Fail the release build if JDK is not 8 to avoid human mistakes and keep all the build resource/tools in sync. 
Build with the check
```
./gradlew build -Prelease
```
Build without check
```
./gradlew build 
```
It's possible verify the JDK for all the build, but it seems more convenient for developers verify only the release. However, we can discuss this decision.

[b/440029547] Add JDK check for the build

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnectorTest.java

- The option query_logs_earliest_timestamp is not supported for Snowflake Assessment. Make it throw an exception if enabled together with assessment mode.
- Move a few lines from addTasksTo to a helper.

Block deprecated option for SF Assessment

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java

The method `getOverrideWhere` shouldn't be changed in #941. Revert to the original implementation.
Also revert the change in `addTasksTo`.

Revert changes to getOverrideWhere

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/NoOpTelemetryStrategy.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/TelemetryProcessor.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/TelemetryStrategy.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/TelemetryStrategyFactory.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/WriteTelemetryStrategy.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/Main.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/TelemetryStrategyTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/clouddumper/MainTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractConnectorExecutionTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnectorTest.java

removed duplicate main instances
moved logic from main to DumperMetadata.class
DumperMetadata.run functions overridden
Deprecated upper mentioned run functions of DumperMetadata.class

refactor and diagnostics flag

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/Connector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/airflow/AirflowConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/airflow/AirflowConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieConnectorTest.java

- Add a method `validateForConnector` called by `AbstractSnowflakeConnector#validate`. The method `validate` handles common checks for the data source, while `validateForConnector` handles checks for a specific connector, e.g. `snowflake-logs`. This is done to ensure that a connector doesn't accidentally skip common validation.
- Add `Nonnull` to the param of `validate`. We don't expect `ConnectorArguments` to be null.
- Make `validateDateRange` non-default. This method is not core connector functionality, it doesn't depend on the connector instance and it shouldn't be overridden. A static method fits better for the usage.
- Simplify some checks in `validateDateRange` to make it less nested.

Fixes for Connector#validate

---

.github/workflows/reports.yml
.github/workflows/tests.yml
dumper/app/build.gradle

Add test coverage reports to PRs for Dumper only for now.
Next steps:
1.  apply to all the modules
2. add minimal test coverage as a mandatory check
3. publish with the releases

[b440295519] Add test coverage report to PRs

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java

This is the first step of a refactor, which is meant to simplify how the queries are built for assessment.
Change the flow of assessment to avoid the partial-substitution trick while creating tasks:
```java
String overrideWhere = arguments.getDefinition(propertyWhere);
if (overrideWhere != null) {
// Partially format the SQL template by re-introducing the first format specifier.
return String.format(defaultSql, "%1$s", " WHERE " + overrideWhere);
}
```
Instead, apply both substitutions in a single step (using `AssessmentQuery#substitute`).

[b/441876236] Refactor: don't "partially format" in Assessment flow

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnectorTest.java

- Add more unit tests
- Don't extend AbstractSnowflakeConnectorExecutionTest - in general it's not needed, add subclass in the only test that uses it
- Small changes for testability: extract code to methods, add `WHERE 1=1` to one of the queries to simplify formatting

Testing: Better unit tests for Snowflake

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnectorTest.java

The category of this task was broken by an earlier change.

Fix: acceleration history task should be optional

---

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeYamlSummaryTask.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnectorTest.java
dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeYamlSummaryTaskTest.java

Provide simple feedback to users running Snowflake extraction.
- Add an additional, user-readable file - `snowflake.yaml`.
- Add a task which generates this file to the connectors: `snowflake`, `snowflake-logs`, `snowflake-lite`.
An example of file contents (assessment enabled, detected 17 warehouses on user system):
```yaml
metadata:
assessment: true
warehouse_count: 17
```

Add a summary YAML for Snowflake
