google/dwh-migration-tools

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/LogsConnector.java
=> Add `-logs` suffix to default log archive file name

README.md, client/README.md
- specify the assumed `pwd` for commands in `client/README.md`
- use `bin/*` commands
=> Use `bin/dwh-migration-*` commands in documentation

dumper-integration-tests/redshift-tests/build.gradle, dumper-integration-tests/redshift-tests/src/main/java/com/google/base/TestBase.java, dumper-integration-tests/redshift-tests/src/main/java/com/google/base/TestConstants.java, dumper-integration-tests/redshift-tests/src/main/java/com/google/sql/SqlUtil.java, dumper-integration-tests/redshift-tests/src/main/resources/logging.properties, dumper-integration-tests/redshift-tests/src/test/java/com/google/integration/RedshiftTest.java, dumper/settings.gradle
1. Test Automation Framework skeleton in Java
2. Gradle config with most likely deps for tests
3. Template Test with place holders for further functionality
4. Logging props
5. Base main classes for testing and other utility needs
6. Code style in accordance with google-formatter-plugin
7. Also this PR is a verification step that EPAM team has accesses and permissions
=> Initial commit

README.md, client/CONTRIBUTING.md, dumper/CONTRIBUTING.md
Initial commit for `README` and dumper's `CONTRIBUTING` pages.
=> Write a proper README file, add contribution instructions for dumper

dumper-integration-tests/redshift-tests/build.gradle, dumper-integration-tests/redshift-tests/src/main/java/com/google/base/TestBase.java, dumper-integration-tests/redshift-tests/src/main/java/com/google/base/TestConstants.java, dumper-integration-tests/redshift-tests/src/main/java/com/google/sql/SqlUtil.java, dumper-integration-tests/redshift-tests/src/main/resources/logging.properties, dumper-integration-tests/redshift-tests/src/test/java/com/google/integration/RedshiftTest.java
=> Dev rebase onto Main

.gitignore, client/Makefile, client/batch_sql_translator.py, client/config_parser.py, client/gcloud_auth_helper.py, client/gcs_util.py, client/macro_processor.py, client/main.py, client/object_mapping_parser.py, client/pyproject.toml, client/requirements_dev.txt
Note that `mypy` is an optional type checker.  Users can still modify their forks without worrying about whether their modifications type check. It is however recommended to run `make check` before submitting a PR back upstream.
=> Use mypy, the canonical Python type checker.

client/dwh_migration_client/batch_sql_translator.py, client/dwh_migration_client/config_parser.py, client/dwh_migration_client/gcloud_auth_helper.py, client/dwh_migration_client/gcs_util.py, client/dwh_migration_client/macro_processor.py, client/dwh_migration_client/main.py, client/dwh_migration_client/object_mapping_parser.py
This allows us to support log message timestamps, levels and eventually thread name.
=> Use a proper logger.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/JdbcPropBuilder.java
Password with percentage sign are not handled correctly by (at least) the Redshift connector.
=> Encode properties in JDBC URL for Redshift.

client/dwh_migration_client/batch_sql_translator.py, client/dwh_migration_client/config_parser.py, client/dwh_migration_client/gcloud_auth_helper.py, client/dwh_migration_client/gcs_util.py, client/dwh_migration_client/macro_processor.py, client/dwh_migration_client/object_mapping_parser.py, client/dwh_migration_client/validation.py
If we have settled on Python 3.6+ or 3.7+ (b/237219199) then we can and should use f-strings.
=> Use Python f-strings.

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle, dumper/app/build.gradle
=> Include vendor JDBC drivers and license assertions

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle
* Fixes b/237715075 (option 2)
=> Dumper: Compile with compatibility=1.8.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
Per @ajwelch4 's suggestion via b/238930130.
=> Remove post-dump reference to Groovy configuration.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/annotations/RespectsArgumentAssessment.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
This clashes a bit with #77 in terms of flag definition. I will reuse the code from it if it is merged earlier
=> Add "--assessment" flag, order Redshift raw logs if it is enabled

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/JsonResponseFile.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/JsonResponseFileTest.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/TeradataLogsDumpFormat.java
These were changes that had diverged locally which now have to be exported again.
=> Export divergent changes

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/netezza/NetezzaMetadataConnector.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/NetezzaMetadataDumpFormat.java
Metadata is placed in `_v_table_dist_map` system view.
=> Dump Netezza's table distribution metadata

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/HiveMetadataDumpFormat.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Function.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
I decided to not put it under `--assessment` flag since this doesn't make much difference anyway – I assume we won't expect many UDFs
=> Add owner info and create time to Hive functions task

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/HiveMetadataDumpFormat.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Database.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
Tested on Dataproc clusters running Hive v2 and v3
=> Add Databases task to capture databases metadata for Assessment

client/README.md, client/bqms_run/hooks.py, client/bqms_run/ksh.py, client/examples/teradata/bteq/clean.sh, client/examples/teradata/bteq/config/config.yaml, client/examples/teradata/bteq/deprovision.sh, client/examples/teradata/bteq/input/commented.ksh, client/examples/teradata/bteq/input/empty.ksh, client/examples/teradata/bteq/input/foo.sql, client/examples/teradata/bteq/input/no-prefix.ksh, client/examples/teradata/bteq/input/simple.ksh, client/examples/teradata/bteq/input/with-flags.ksh, client/examples/teradata/bteq/input/with-prefix.ksh, client/examples/teradata/bteq/provision.sh, client/examples/teradata/bteq/run.sh, client/noxfile.py, client/pyproject.toml, client/tests/integration/test_bteq.py, client/tests/unit/test_ksh.input/commented.ksh, client/tests/unit/test_ksh.input/empty.ksh, client/tests/unit/test_ksh.input/no-prefix.ksh, client/tests/unit/test_ksh.input/simple.ksh, client/tests/unit/test_ksh.input/with-flags.ksh, client/tests/unit/test_ksh.input/with-prefix.ksh, client/tests/unit/test_ksh.py
=> Bteq: support extraction of heredoc SQL fragments from KSH inputs

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java
```
*******************************************************************
* Task Summary:
* Task SUCCEEDED (REQUIRED) Write database.csv from:
......
SELECT * FROM table
*******************************************************************
* Metadata has been saved to dwh-migration-redshift-metadata.zip
*******************************************************************
* 35 TASKS SUCCEEDED
*******************************************************************
```
=> use star decorated logger

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java
Add possibility to limit the number of rows returned from the DBC.TableSizeV table.
=> Add --max-tablesizev-rows parameter.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalTest.java
This would be required for future features. See #133
=> zoned interval spanning

buildSrc/src/main/groovy/dwh-migration-dumper.java-common-conventions.gradle, dumper/lib-ext-hive-metastore/build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Upgrade BigQuery client

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
This is part of breaking down #153
=> remove relation of `Teradata14LogsConnector` and `TeradataLogsConnector`

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java
Reverts google/dwh-migration-tools#160
=> Revert "remove relation of `Teradata14LogsConnector` and `TeradataLogsConnector`"

client/bqms_run/gcp/bqms/request.py, client/poetry.lock, client/pyproject.toml
- Update to latest cloud library `0.11.0`
- Pass `python-client` as source description
=> Add request field with default value for python CLI

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalTest.java
This would also be needed for #133
=> add equality check for intervals

client/README.md, client/bqms_run/encoding.py, client/pyproject.toml
Tested end-to-end installation + execution on GCE instances:
=> ICU: make optional

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/AbstractTeradataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilityLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectIntervalTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/Summary.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/task/JdbcSelectTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/task/SummaryTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/test/DumperTestUtils.java
=> introduce task summary

client/README.md, client/bqms_run/gcp/bqms/translation_type.py
Minor bug fix about folder name mix-match
=> Update README for client

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/SnowflakeMetadataDumpFormat.java
- it seems the only way to get the size of the warehouse
=> dump results of SHOW WAREHOUSES for Snowflake

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
Additionally, remove the `TODO` comment about creating a base class of the `TeradataLogsConnector`, because it is already created.
=> Format ConnectorArguments and TeradataLogsConnector.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
The new option is needed to specify the alternative location of utility logs, similarly to how `--query-log-alternates` command-line option already provides the alternative location for query logs.
=> Add command-line option for utility logs table. 

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataAssessmentLogsJdbcTaskTest.java
LogDate is part of Partitioned Primary Index of both tables, so it needs to be part of the JOIN condition.
=> Add LogDate to the JOIN condition

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java
[Language manual](https://cwiki.apache.org/confluence/display/hive/languagemanual+ddl) explicitly states `The uses of SCHEMA and DATABASE are interchangeable – they mean the same thing`. Assessment uses "database" term. The current option potentially brings a confusion in the public documentation.
Schema option is only used in Hive and Oracle connectors (where it means, well, [a user](https://www.janbasktraining.com/community/sql-server/how-is-oracle-schema-different-from-database-or-user#:~:text=In%20Oracle%20schemas%20and%20users,that%20belong%20to%20that%20account.) ), while Database option is used in Teradata and Netezza connectors specifically to filter by database name, so the PR makes Hive connector the same.
=> Use database predicate instead of schema predicate

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/TimeTruncator.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalIterable.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalIterableGenerator.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/bigquery/BigQueryLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/generic/GenericConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/Teradata14LogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalIterableTest.java
=> Replace with duration

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftRawLogsConnector.java
similar to https://github.com/google/dwh-migration-tools/pull/287
=> Add `query-log-rotation-frequency` flag for redshift

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java
Add two command-line options to provide alternative location of Teradata resource usage tables: ResUsageScpu and ResUsageSpma. The options are:
```
-Dteradata-logs.res-usage-scpu-table
-Dteradata-logs.res-usage-spma-table
```
=> Add alternative location for Teradata resource usage tables

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/SummaryPrinter.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftClusterNodesTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftClusterUsageMetricsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractTask.java
Extract the formatting of the summary double-line to the separate method `joinSummaryDoubleLine`.
=> Code cleanup - joinSummaryDoubleLine

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java
The files and directories created in test were not always cleaned up due to the `file` field being either null or not assigned the correct file to delete. I'm adding `TopLevelTestFile` enum with all the possible files and directories created in tests in the `MetadataDumperTest` class and deleting them at the beginning and at the end of each test.
=> Fix cleaning up files and directories in test

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/DefaultArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractAwsApiTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/MetadataQueryGenerator.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/QueryLogTableNamesResolver.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtils.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/OptionalUtils.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/PropertyParser.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/HadoopSaslQopConverterTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataUtilsTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/MemoizationUtilTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/OptionalUtilsTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/PropertyParserTest.java
Move general-purpose methods related to `Optional` from `TeradataUtils` to `OptionalUtils`. Use the methods to simplify code.
=> Add OptionalUtils

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/DefaultArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/AbstractAwsApiTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/MetadataQueryGenerator.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/QueryLogTableNamesResolver.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsJdbcTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/OptionalUtils.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/utils/PropertyParser.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/utils/OptionalUtilsTest.java
Rename methods as discussed in the review of #355.
optionalIf to optionallyWhen
nonEmpty to optionallyIfNotEmpty
=> Rename OptionalUtils methods

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/AbstractClouderaTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaClustersTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaConnectorUtils.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaHandle.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaHdfsUsageTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaHostsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaManagerConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/ClouderaServicesTask.java
1. Write output from cloudera connector tasks as jsonl
2. Add cluster utilization to output dumps
3. Reformats cloudera connector code
=>  Write cloudera information as jsonl and add cluster utilization

dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
The PR #328 was merged recently without resolving the spotless violations. This change is to reformat code to make it pass the spotless check.
=> Reformat code

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java
Extract master keys and save them in the `master-keys.csv` file.
=> [b/343058608] Extract master keys from HMS

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/ThriftJsonSerializer.java, dumper/lib-ext-hive-metastore/src/test/java/com/google/edwmigration/dumper/ext/hive/metastore/ThriftJsonSerializerTest.java
Extract functions from HMS in JSONL format.
=> [b/343064637] Extract functions from HMS

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_Superset.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/HiveMetastoreThriftClient_v2_3_6.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/Table.java, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/ThriftJsonSerializer.java
Extracted primary keys are added to the existing file `tables-raw.jsonl` as a new field `primaryKeys`.
=> [b/343069385] Extract primary keys from HMS

dumper/app/build.gradle
This PR adds missing links to the dependency project and license file. It covers all the current dependencies.
=> [b/346977975] Add missing project and license urls for the new dependencies

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/native/table-types-dtl.sql
=> [b/341297017] Add table-types-dtl.sql

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/native/m-view-types.sql
=> [b/341297017] Add m-view-types.sql

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/native/dtl-source-code.sql
=> [b/341297017] Add dtl-source-code.sql

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/native/data-types.sql
=> [b/341297017] Add data-types.sql

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/MessageTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorExceptions.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQuery.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/MessageTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleConnectorExceptionsTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleStatsQueryTest.java
- extract MessageTask to a separate file
- create MessageTaskTest and add basic tests
- remove duplicate `Lists.transform` formatting logic
=> Add tests for MessageTask

dumper/app/src/main/resources/oracle-stats/native/used-space-details.sql
Add a new column to used-space-details
=> Add the SEGMENT_NAME column

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsJdbcTaskTest.java
Add tests for StatsJdbcTask to improve coverage of the Oracle connectors.
=> Add a test class for StatsJdbcTask

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java
Filename: `master-keys.csv`
Contents:
```
MasterKey
sample-master-key-abc
sample-master-key-2
```
Filename: `master-keys.jsonl`
Contents:
```
{"masterKey":"sample-master-key-abc"}
{"masterKey":"sample-master-key-2"}
```
=> [b/343058608] Change the format of master-keys file from csv to jsonl

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnectorTest.java, dumper/lib-ext-hive-metastore/build.gradle, dumper/lib-ext-hive-metastore/src/main/java/com/google/edwmigration/dumper/ext/hive/metastore/DelegationToken.java
Filename: `delegation-tokens.csv`
Contents:
```
Identifier,Token
sample-token-identifier-123,sample-token-xyz
sample-token-identifier-456,sample-token-qwe
```
Filename: `delegation-tokens.jsonl`
Contents:
```
{"identifier":"sample-token-identifier-123","token":"sample-token-xyz"}
{"identifier":"sample-token-identifier-456","token":"sample-token-qwe"}
```
=> [b/343058965] Change delegation tokens file from csv to jsonl

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractTask.java
Partitions for all the tables were written to `partitions.jsonl` file, which made it difficult to access partitions of a single table. In this PR I'm writing partitions of each table to a separate file `partitions-<database_name>-<table_name>.jsonl`.
=> [b/343063007] Split partitions into files per table

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/dba/native/db-objects-synonym-public.sql, dumper/app/src/main/resources/oracle-stats/dba/native/db-objects.sql
- add db-objects.sql for non-cdb
- add db-objects-synonym-public for non-cdb
=> [b/352468287] Add non-CDB versions of both db-objects SQLs

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/dba/native/app-schemas-pdbs.sql, dumper/app/src/main/resources/oracle-stats/dba/native/data-types.sql, dumper/app/src/main/resources/oracle-stats/dba/native/db-info.sql
- add DBA versions of data-types and db-info
- fill in the app-schemas-pdbs implementation
=> [b/352468287] Add non-CDB versions of db-info and data-types

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/dba/native/table-types-dtl.sql, dumper/app/src/main/resources/oracle-stats/dba/native/used-space-details.sql, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java
- add non-CDB version of table-types-dtl
- add non-CDB used-space-details
=> [b/352468287] Add non-CDB table-types-dtl and used-space-details SQLs

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/ScanContext.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/HdfsPermissionExtractionDumpFormat.java
Also moved the FileSize column right after FileType
=> [b/355650388] Add FileType column in hdfs-permissions.csv file

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/QueryGroup.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGenerator.java, dumper/app/src/main/resources/oracle-stats/cdb/awr/hist-cmd-types-awr.sql, dumper/app/src/main/resources/oracle-stats/cdb/awr/source-conn-latest.sql, dumper/app/src/main/resources/oracle-stats/cdb/awr/sql-stats-awr.sql, dumper/app/src/main/resources/oracle-stats/dba/awr/sql-stats-awr.sql, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/StatsTaskListGeneratorTest.java
- enable non-CDB queries for AWR
- add non-CDB sql-stats-awr
=> [b/352468287] Add non-CDB sql-stats-awr

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataTablesValidatorTask.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataLogsConnectorTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataTablesValidatorTaskTest.java
Please double check if the logic of applying the validation is correct and properly tested.
=> [b/369075732] Add Teradata tables validation for additional command line options

dumper/app/build.gradle
b/370481697 revealed multiple issues in the report. Some were related to missing license links in this project's list. This PR aims to fix them.
=> Update compliance information with license links

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/AbstractOracleConnector.java
=> [b/370703701] Add more descriptive connection error message for Oracle

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java
- fix: information_schema isn't not properly disabled for assessment use in metadata connector
- snowflake-lite: always behave as if the assessment flag was provided
- snowflake-lite: remove references to information_schema from the connector
=> [b/376638949] Don't use INFORMATION_SCHEMA in snowflake-lite

.github/dependabot.yml
Configuration for JDK 8
https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#artifacts
=> [improve] configure dependabot for hikari and JDK 8

dumper/app/src/main/resources/oracle-stats/cdb/awr/segment-stats.sql, dumper/app/src/main/resources/oracle-stats/dba/awr/segment-stats.sql
Add 3 new columns for `segment-stats.csv` :
`SegStatObj.owner,  SegStatObj.object_name,  SegStatObj.object_type`
=> Adding new columns for segment-stats.sql

.github/dependabot.yml
Configurations for Java 8 support 
https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range
=> Update dependabot config for spring framework

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsHandle.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/oracle/OracleMetadataConnector.java
(This is a supplement to https://github.com/google/dwh-migration-tools/pull/635)
=> Kerberos auth for HdfsConnector: Applying mods suggested by Radek

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTaskTest.java, dumper/app/src/test/resources/cloudera/manager/cluster-cpu-status.json
- Add a task to fetch cpu usage statistics from the Cloudera cluster
The task collects fetched data into the following files:
=> [/b376629469] Cloudera timeseries for CPU usage

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaTimeSeriesTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/ApiClusterDTO.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/ApiClusterListDTO.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/ApiHostDTO.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/ApiHostListDTO.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/CMFHostDTO.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/dto/CMFHostListDTO.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTaskTest.java
=> Rename classes -Dto -> -DTO

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaManagerTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaAPIHostsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaCMFHostsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClusterCPUChartTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostRAMChartTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerHandle.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaHostComponentsTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaManagerHandleTest.java
Dump additional Cloudera API https://archive.cloudera.com/cm7/7.11.3.0/generic/jar/cm_api/apidocs/resource_HostsResource.html#resource_HostsResource_HostsResourceV55_getHostComponents_GET 
Use wiremock for unit tests
=> [b/380000872] Dump hosts components

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaClustersTaskTest.java
Example of ClustersTask unit-test with https://wiremock.org/
Tests with wiremock:
1. clusterNotProvided_wiremock_success
2. clusterProvided_wiremock_success
Tests with mockito only:
1. clusterNotProvided_success
2. clusterProvided_success
I leave 2 versions of test for now to simplify comparison. Tests coverage is the same but in case of WireMock the tests makes real http calls to localhost.
=> [b/377651080] rewrite cluster test with wiremock

dumper/app/build.gradle
Update the build file so test coverage report will be automatically generated at 'build/reports/jacocoHtml'
=> [b/394256261] [Dumper] Publish test coverage

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ranger/RangerPageIterator.java
Improve error message on Ranger connector to make actual exception message show on the top of the stacktrace and on run summary.
=> [b/394561079] better error message for ranger connector

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/AbstractClouderaYarnApplicationTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaYarnApplicationTypeTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaYarnApplicationsTask.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/cloudera/manager/ClouderaYarnApplicationTypeTaskTest.java
For example application type can be: "Oozie Launcher"
=> Fix: Filter by YARN application type which contains space characters

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/LiteTimeSeriesTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeLiteConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java
Provide a time range of extracted data in a separate task.
=> [b/398815530] Add start and end dates to snowflake-lite output

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ranger/RangerConnectorTasksTest.java
Gradle command to apply code style is `./gradlew :dumper:app:spotlessApply`
=> [OPS] fix code style

README.md, dumper/README.md
Java 8 is required for compiling
=> [OPS] Update README.md

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/airflow/AirflowConnector.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/airflow/AirflowConnectorTest.java
Table is required for clarified requirements.
Next steps:
1. add start/end optional date parameters
=> [b/390590500] add additional table to airflow connector

README.md
Add separate section for compilation.
Next step: add information about `dbsync` module.
=> Add compile section to README.md

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java
- Add the predicate `"deleted IS NULL AND schema_dropped IS NULL AND table_dropped IS NULL"` to the filter on table storage metrics
- Provide the select list and csv header explicitly. It's verbose, but makes it easier to see what the actual values are
=> [b/404462380] Filter out metrics of deleted objects

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/MetadataView.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakePlanner.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeAccountUsageMetadataConnectorTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnectorTest.java, dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/SnowflakeMetadataDumpFormat.java
=> Revert "[b/394312229] Dump Snowflake external table metadata (#746)"

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/HadoopMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/HdfsExtractionConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hive/HiveMetadataConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ranger/RangerConnector.java
Add timestamp to all connectors related to Hadoop.
=> [OPS] add timestamp to Hadoop connectors

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/AbstractOozieJobsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieClientFactory.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieConnector.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieCoordinatorJobsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieInfoTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieServersTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieWorkflowJobsTask.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieClientFactoryTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieConnectorTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieCoordinatorJobsTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieWorkflowJobsTaskTest.java
Dump:
1. Oozie url
2. Oozie servers
3. Server version
4. Coord jobs
Rename: oozie_jobs.csv -> oozie_workflow_jobs.csv.  Server changes are required.
=> [b/407529689] More Oozie info

dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/SnowflakeMetadataConnectorTest.java
=> [Snowflake Connector] Add tests for connector's SQL overrides.

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/AbstractOozieJobsTask.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/AbstractTask.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieBundleJobsTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieCoordinatorJobsTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/hadoop/oozie/OozieWorkflowJobsTaskTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/task/CsvFormatTest.java, dumper/app/src/test/resources/oozie/expected-jobs-byenddate.csv, dumper/app/src/test/resources/oozie/expected-jobs.csv
1. get props from parent classes
2. cover with unit tests
=> [OPS] get props from parent class and add tests

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/StartUpMetainformationPrinter.java
Verified for:
1. Java 8, 11, 17, 21.
2. Single and multiple jars in class path.
=> [OPS] fix banner load

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/redshift/RedshiftMetadataConnector.java
=> Fix: type errors related to xids in Redshift

dumper/app/build.gradle
=> [OPS] Add some fun to a developer's life

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/task/TaskGroup.java
=> [OPS] Use immutable list in TaskGroup

dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GcsyncClient.java, dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GcsyncMain.java, dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GcsyncTask.java, dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/GenerateCheckSumMain.java, dbsync/gcsync/src/main/java/com/google/edwmigration/dbsync/gcsync/ReconstructFilesMain.java, dbsync/storage-gcs/src/main/java/com/google/edwmigration/dbsync/storage/gcs/GcsByteSource.java
This optimization improves performance in some scenarios but makes it worse when blocks are swapped.
=> Revert an optimization in GcsBytesource (and some automatic formatting changes)

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/Main.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/MetadataDumper.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/StartUpMetaInfoProcessor.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/TelemetryProcessor.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/TelemetryWriter.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/clouddumper/Main.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/metrics/ClientTelemetry.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/metrics/DumperMetadata.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/metrics/DumperRunMetrics.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/metrics/EventType.java, dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/metrics/TelemetryPayload.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/MetadataDumperTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/AbstractConnectorExecutionTest.java, dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/teradata/TeradataMetadataConnectorTest.java
changed Telemetry object to follow open to extension closed to modification principle
=> Refactored Telemetry object 

build.gradle
Add a parameter to use in CI builds as well, not only in releases.
=> [b/440029547] Add JDK check CI builds

.github/workflows/gradle.yml
Workflow for testing and building
=> [b/440295519] Create gradle build & test setup

dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ConnectorProperty.java
It's not important PR. just to verify that the PR will trigger internal Google jobs.
=> [OPS] remove not required public declaration
